### ISSUE TITLE
Split Decision distances

### ISSUE THREAD

**Issue by the-IonMan** [SergioMendolia/r4s#54]
Hi,
great useful tool for our gaming group and the whole WMH community!
The dimesnsion in scenario 5 (Split decision) seem not to be according to the latest version after CID (https://home.privateerpress.com/wp-content/uploads/2021/06/Steamroller-Rules-2021_v4.pdf)

**Comment by SergioMendolia** [comment]
Hey thanks for reporting! I just deployed the correct one!

**Comment by the-IonMan** [comment]
👍
